### ISSUE TITLE
API Connection Error (Failure not caught)

### ISSUE THREAD

**Issue by manuelPartida** [launchdarkly/relayCommander#10]
launchdarkly_api.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Accept,Content-Type,Content-Length,Accept-Encoding,Authorization,X-Requested-With,X-LD-Private,X-LD-AccountId,X-LD-EnvId,X-LD-PrjId,X-LaunchDarkly-Event-Schema,X-LaunchDarkly-User-Agent', 'Access-Control-Allow-Methods': 'OPTIONS, HEAD, GET, PATCH, DELETE', 'Access-Control-Allow-Origin': '*', 'Access-Control-Max-Age': '300', 'Set-Cookie': '_ld_csrf=MTU0Nzc2NTc4MXxJbFZ2YWxneE9EaG1NVFJaYzNsNVFsVldRVlZNUzBNMEwwczNjRWxrTlUxalZHdFFNMG96TjI0MFVVMDlJZ289fE1IPL1kF4K94S_hhxnuTJ4-onghKrBuPgIzh03sNeU5; Path=/; HttpOnly; Secure', 'X-Csrf-Token': 'fbsaG1mEnQKainl+ie0oiebYdaLD5jzz1Wqt8PWsgL4vM83MlptKhLZBWSrd6COhyOdeGIuRr++bKVrXi0thvQ==', 'Content-Length': '0', 'Accept-Ranges': 'bytes', 'Date': 'Thu, 17 Jan 2019 22:56:21 GMT', 'Via': '1.1 varnish', 'Connection': 'keep-alive', 'X-Served-By': 'cache-sea1051-SEA', 'X-Cache': 'MISS', 'X-Cache-Hits': '0', 'X-Timer': 'S1547765782.542979,VS0,VE69', 'Vary': 'Accept-Encoding, Origin', 'Age': '0'})

/bin/sh: 1: cannot open _io.TextIOWrapper: No such file
LaunchDarkly is now update to date

**Comment by levlaz** [comment]
It looks like there are two issues here. 

1. The 401 coming from the API. We partially address this by adding a check to ensure that the LD ENV VAR is set, we should add an additional try/except to catch the 401 error if the key is wrong or lacks the correct permissions. 

2. The TextIOWrapper thing was fixed in https://github.com/launchdarkly/relayCommander/commit/11f2d1240a8d52162e67031458784c0256a51eba
